### ISSUE TITLE
Error executive

### ISSUE THREAD

**Issue by Rub21** [zeekay/executive#28]
Hey, suddenly this error appear in my app when I use node  v.4.4.x

```
/home/rub/apps/test/node_modules/executive/dist/lib.js:226
var parse = function(args, opts = {}) {
                                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by zeekay** [comment]
Good catch, we should avoid targeting newer JavaScript features for broadest compatibility. Fixed in 1.2.6.
